#nullable enable

using System;
using UnityEngine;
using UnityEngine.UIElements;

namespace LumaFlow {

    /// <summary>
    /// Selects a semantic button treatment from the nearest <see cref="Theme"/>.
    /// </summary>
    public enum ButtonVariant {
        Primary,
        Secondary,
        Destructive
    }

    public readonly struct IconData {
        public IconData(string name, string resourceId) {
            if (string.IsNullOrWhiteSpace(name)) throw new ArgumentException("Icon name is required.", nameof(name));
            if (string.IsNullOrWhiteSpace(resourceId)) throw new ArgumentException("Icon resource id is required.", nameof(resourceId));
            Name = name;
            ResourceId = resourceId;
        }
        public string Name { get; }
        public string ResourceId { get; }
        public bool IsDefined => !string.IsNullOrWhiteSpace(Name) && !string.IsNullOrWhiteSpace(ResourceId);
    }

    public static class LumaIcons {
        // <auto-generated: LumaIcons>
        // Generated by Tools/LumaFlow/Icons/generate_luma_icons.py. Do not edit by hand.
        public static IconData Archive { get; } = new("Archive", "LumaFlowIcons/archive");
        public static IconData ArrowDown { get; } = new("ArrowDown", "LumaFlowIcons/arrow-down");
        public static IconData ArrowLeft { get; } = new("ArrowLeft", "LumaFlowIcons/arrow-left");
        public static IconData ArrowRight { get; } = new("ArrowRight", "LumaFlowIcons/arrow-right");
        public static IconData ArrowUp { get; } = new("ArrowUp", "LumaFlowIcons/arrow-up");
        public static IconData Bell { get; } = new("Bell", "LumaFlowIcons/bell");
        public static IconData Braces { get; } = new("Braces", "LumaFlowIcons/braces");
        public static IconData Bug { get; } = new("Bug", "LumaFlowIcons/bug");
        public static IconData Calendar { get; } = new("Calendar", "LumaFlowIcons/calendar");
        public static IconData Check { get; } = new("Check", "LumaFlowIcons/check");
        public static IconData ChevronDown { get; } = new("ChevronDown", "LumaFlowIcons/chevron-down");
        public static IconData ChevronLeft { get; } = new("ChevronLeft", "LumaFlowIcons/chevron-left");
        public static IconData ChevronRight { get; } = new("ChevronRight", "LumaFlowIcons/chevron-right");
        public static IconData ChevronUp { get; } = new("ChevronUp", "LumaFlowIcons/chevron-up");
        public static IconData ChevronsDown { get; } = new("ChevronsDown", "LumaFlowIcons/chevrons-down");
        public static IconData ChevronsLeft { get; } = new("ChevronsLeft", "LumaFlowIcons/chevrons-left");
        public static IconData ChevronsRight { get; } = new("ChevronsRight", "LumaFlowIcons/chevrons-right");
        public static IconData ChevronsUp { get; } = new("ChevronsUp", "LumaFlowIcons/chevrons-up");
        public static IconData Clipboard { get; } = new("Clipboard", "LumaFlowIcons/clipboard");
        public static IconData Clock { get; } = new("Clock", "LumaFlowIcons/clock");
        public static IconData Close { get; } = new("Close", "LumaFlowIcons/x");
        public static IconData Code { get; } = new("Code", "LumaFlowIcons/code");
        public static IconData Columns { get; } = new("Columns", "LumaFlowIcons/columns-3");
        public static IconData Copy { get; } = new("Copy", "LumaFlowIcons/copy");
        public static IconData Database { get; } = new("Database", "LumaFlowIcons/database");
        public static IconData Delete { get; } = new("Delete", "LumaFlowIcons/trash-2");
        public static IconData Download { get; } = new("Download", "LumaFlowIcons/download");
        public static IconData Edit { get; } = new("Edit", "LumaFlowIcons/pencil");
        public static IconData Error { get; } = new("Error", "LumaFlowIcons/circle-x");
        public static IconData ExternalLink { get; } = new("ExternalLink", "LumaFlowIcons/external-link");
        public static IconData Eye { get; } = new("Eye", "LumaFlowIcons/eye");
        public static IconData EyeOff { get; } = new("EyeOff", "LumaFlowIcons/eye-off");
        public static IconData File { get; } = new("File", "LumaFlowIcons/file");
        public static IconData FileText { get; } = new("FileText", "LumaFlowIcons/file-text");
        public static IconData Filter { get; } = new("Filter", "LumaFlowIcons/funnel");
        public static IconData Folder { get; } = new("Folder", "LumaFlowIcons/folder");
        public static IconData FolderOpen { get; } = new("FolderOpen", "LumaFlowIcons/folder-open");
        public static IconData GitBranch { get; } = new("GitBranch", "LumaFlowIcons/git-branch");
        public static IconData GitCommit { get; } = new("GitCommit", "LumaFlowIcons/git-commit-horizontal");
        public static IconData Globe { get; } = new("Globe", "LumaFlowIcons/globe");
        public static IconData Grid { get; } = new("Grid", "LumaFlowIcons/grid-2x2");
        public static IconData GripVertical { get; } = new("GripVertical", "LumaFlowIcons/grip-vertical");
        public static IconData Hammer { get; } = new("Hammer", "LumaFlowIcons/hammer");
        public static IconData Headphones { get; } = new("Headphones", "LumaFlowIcons/headphones");
        public static IconData Help { get; } = new("Help", "LumaFlowIcons/circle-question-mark");
        public static IconData Home { get; } = new("Home", "LumaFlowIcons/house");
        public static IconData Image { get; } = new("Image", "LumaFlowIcons/image");
        public static IconData Info { get; } = new("Info", "LumaFlowIcons/info");
        public static IconData Key { get; } = new("Key", "LumaFlowIcons/key-round");
        public static IconData Library { get; } = new("Library", "LumaFlowIcons/library");
        public static IconData Link { get; } = new("Link", "LumaFlowIcons/link");
        public static IconData List { get; } = new("List", "LumaFlowIcons/list");
        public static IconData Loader { get; } = new("Loader", "LumaFlowIcons/loader-circle");
        public static IconData Lock { get; } = new("Lock", "LumaFlowIcons/lock");
        public static IconData Mail { get; } = new("Mail", "LumaFlowIcons/mail");
        public static IconData Maximize { get; } = new("Maximize", "LumaFlowIcons/maximize");
        public static IconData Menu { get; } = new("Menu", "LumaFlowIcons/menu");
        public static IconData Mic { get; } = new("Mic", "LumaFlowIcons/mic");
        public static IconData Minimize { get; } = new("Minimize", "LumaFlowIcons/minimize");
        public static IconData Minus { get; } = new("Minus", "LumaFlowIcons/minus");
        public static IconData MoreHorizontal { get; } = new("MoreHorizontal", "LumaFlowIcons/ellipsis");
        public static IconData MoreVertical { get; } = new("MoreVertical", "LumaFlowIcons/ellipsis-vertical");
        public static IconData Move { get; } = new("Move", "LumaFlowIcons/move");
        public static IconData Music { get; } = new("Music", "LumaFlowIcons/music");
        public static IconData Package { get; } = new("Package", "LumaFlowIcons/package");
        public static IconData PanelLeft { get; } = new("PanelLeft", "LumaFlowIcons/panel-left");
        public static IconData PanelRight { get; } = new("PanelRight", "LumaFlowIcons/panel-right");
        public static IconData Pause { get; } = new("Pause", "LumaFlowIcons/pause");
        public static IconData Play { get; } = new("Play", "LumaFlowIcons/play");
        public static IconData Plus { get; } = new("Plus", "LumaFlowIcons/plus");
        public static IconData Redo { get; } = new("Redo", "LumaFlowIcons/redo-2");
        public static IconData Refresh { get; } = new("Refresh", "LumaFlowIcons/refresh-cw");
        public static IconData Rows { get; } = new("Rows", "LumaFlowIcons/rows-3");
        public static IconData Save { get; } = new("Save", "LumaFlowIcons/save");
        public static IconData Search { get; } = new("Search", "LumaFlowIcons/search");
        public static IconData Server { get; } = new("Server", "LumaFlowIcons/server");
        public static IconData Settings { get; } = new("Settings", "LumaFlowIcons/settings");
        public static IconData Share { get; } = new("Share", "LumaFlowIcons/share-2");
        public static IconData Sidebar { get; } = new("Sidebar", "LumaFlowIcons/panel-left-open");
        public static IconData SkipBack { get; } = new("SkipBack", "LumaFlowIcons/skip-back");
        public static IconData SkipForward { get; } = new("SkipForward", "LumaFlowIcons/skip-forward");
        public static IconData Stop { get; } = new("Stop", "LumaFlowIcons/square");
        public static IconData Success { get; } = new("Success", "LumaFlowIcons/circle-check");
        public static IconData Table { get; } = new("Table", "LumaFlowIcons/table");
        public static IconData Terminal { get; } = new("Terminal", "LumaFlowIcons/terminal");
        public static IconData Undo { get; } = new("Undo", "LumaFlowIcons/undo-2");
        public static IconData Unlock { get; } = new("Unlock", "LumaFlowIcons/lock-open");
        public static IconData Upload { get; } = new("Upload", "LumaFlowIcons/upload");
        public static IconData User { get; } = new("User", "LumaFlowIcons/user");
        public static IconData Users { get; } = new("Users", "LumaFlowIcons/users");
        public static IconData Volume { get; } = new("Volume", "LumaFlowIcons/volume-2");
        public static IconData VolumeLow { get; } = new("VolumeLow", "LumaFlowIcons/volume-1");
        public static IconData VolumeOff { get; } = new("VolumeOff", "LumaFlowIcons/volume-x");
        public static IconData Warning { get; } = new("Warning", "LumaFlowIcons/triangle-alert");
        public static IconData Wrench { get; } = new("Wrench", "LumaFlowIcons/wrench");
        public static IconData LumaFlow { get; } = new("LumaFlow", "LumaFlowIcons/lumaflow");

        public static System.Collections.Generic.IReadOnlyList<IconData> All { get; } =
            System.Array.AsReadOnly(new[]
            {
            Archive,
            ArrowDown,
            ArrowLeft,
            ArrowRight,
            ArrowUp,
            Bell,
            Braces,
            Bug,
            Calendar,
            Check,
            ChevronDown,
            ChevronLeft,
            ChevronRight,
            ChevronUp,
            ChevronsDown,
            ChevronsLeft,
            ChevronsRight,
            ChevronsUp,
            Clipboard,
            Clock,
            Close,
            Code,
            Columns,
            Copy,
            Database,
            Delete,
            Download,
            Edit,
            Error,
            ExternalLink,
            Eye,
            EyeOff,
            File,
            FileText,
            Filter,
            Folder,
            FolderOpen,
            GitBranch,
            GitCommit,
            Globe,
            Grid,
            GripVertical,
            Hammer,
            Headphones,
            Help,
            Home,
            Image,
            Info,
            Key,
            Library,
            Link,
            List,
            Loader,
            Lock,
            Mail,
            Maximize,
            Menu,
            Mic,
            Minimize,
            Minus,
            MoreHorizontal,
            MoreVertical,
            Move,
            Music,
            Package,
            PanelLeft,
            PanelRight,
            Pause,
            Play,
            Plus,
            Redo,
            Refresh,
            Rows,
            Save,
            Search,
            Server,
            Settings,
            Share,
            Sidebar,
            SkipBack,
            SkipForward,
            Stop,
            Success,
            Table,
            Terminal,
            Undo,
            Unlock,
            Upload,
            User,
            Users,
            Volume,
            VolumeLow,
            VolumeOff,
            Warning,
            Wrench,
            LumaFlow,
            });
        // </auto-generated: LumaIcons>
    }

    public sealed class IconThemeData {
        public IconThemeData(float size = 20f, Color? color = null, Color? disabledColor = null) {
            if (float.IsNaN(size) || float.IsInfinity(size) || size <= 0f) throw new ArgumentOutOfRangeException(nameof(size));
            Size = size; Color = color ?? UnityEngine.Color.white; DisabledColor = disabledColor ?? Color;
        }
        public float Size { get; }
        public Color Color { get; }
        public Color DisabledColor { get; }
    }

    public sealed class Icon : Widget {
        public Icon(IconData data, float? size = null, Color? color = null) {
            if (!data.IsDefined) throw new ArgumentException("Icon data is required.", nameof(data));
            if (size is { } explicitSize && (float.IsNaN(explicitSize) || float.IsInfinity(explicitSize) || explicitSize <= 0f)) throw new ArgumentOutOfRangeException(nameof(size));
            Data = data;
            Size = size;
            Color = color;
        }
        public IconData Data { get; }
        public float? Size { get; }
        public Color? Color { get; }
        internal override WidgetNode CreateNode() => new IconNode(this);
    }

    internal sealed class IconNode : WidgetNode {
        public IconNode(Icon widget) : base(widget) { }
        protected override VisualElement CreateElement(BuildContext context) {
            var widget = (Icon)Widget;
            var image = new UnityEngine.UIElements.Image { focusable = false, scaleMode = ScaleMode.ScaleToFit };
            ApplyIcon(image, widget);
            image.style.flexShrink = 0f;
            return image;
        }

        internal override bool TryUpdate(Widget nextWidget) {
            if (!CanUpdateWith(nextWidget) || nextWidget is not Icon icon) return false;
            ReevaluateInheritedDependencies(() =>
            {
                ApplyIcon((UnityEngine.UIElements.Image)Element, icon);
                return true;
            });
            UpdateWidget(icon);
            return true;
        }
        protected override void OnInheritedChanged(InheritedAspect aspect) => ApplyIcon((UnityEngine.UIElements.Image)Element, (Icon)Widget);
        private void ApplyIcon(UnityEngine.UIElements.Image image, Icon widget) {
            var theme = Context.Theme?.IconTheme ?? ThemeData.FallbackIconTheme;
            image.name = $"lumaflow-icon-{widget.Data.Name}";
            image.vectorImage = Resources.Load<VectorImage>(widget.Data.ResourceId);
            image.tintColor = widget.Color ?? theme.Color;
            image.style.width = widget.Size ?? theme.Size;
            image.style.height = widget.Size ?? theme.Size;
        }
    }

    public sealed class IconButton : Widget {
        /// <summary>Creates an icon button whose callback receives its mounted native anchor.</summary>
        public IconButton(
            IconData icon,
            Action<VisualElement> onPressed,
            string? tooltip = null,
            bool enabled = true,
            float hitSize = 40f,
            ButtonVariant variant = ButtonVariant.Secondary,
            ButtonStyle? style = null,
            FocusNode? focusNode = null) {
            if (!icon.IsDefined) throw new ArgumentException("Icon data is required.", nameof(icon));
            if (float.IsNaN(hitSize) || float.IsInfinity(hitSize) || hitSize <= 0f) throw new ArgumentOutOfRangeException(nameof(hitSize));
            if (!Enum.IsDefined(typeof(ButtonVariant), variant)) throw new ArgumentOutOfRangeException(nameof(variant));
            Icon = icon;
            OnPressed = null;
            OnPressedWithAnchor = onPressed ?? throw new ArgumentNullException(nameof(onPressed));
            Tooltip = tooltip;
            Enabled = enabled;
            HitSize = hitSize;
            Variant = variant;
            Style = style;
            FocusNode = focusNode;
        }

        public IconButton(
            IconData icon,
            Action onPressed,
            string? tooltip = null,
            bool enabled = true,
            float hitSize = 40f,
            ButtonVariant variant = ButtonVariant.Secondary,
            ButtonStyle? style = null,
            FocusNode? focusNode = null) {
            if (!icon.IsDefined) throw new ArgumentException("Icon data is required.", nameof(icon));
            if (float.IsNaN(hitSize) || float.IsInfinity(hitSize) || hitSize <= 0f) throw new ArgumentOutOfRangeException(nameof(hitSize));
            if (!Enum.IsDefined(typeof(ButtonVariant), variant)) throw new ArgumentOutOfRangeException(nameof(variant));
            Icon = icon;
            OnPressed = onPressed ?? throw new ArgumentNullException(nameof(onPressed));
            Tooltip = tooltip;
            Enabled = enabled;
            HitSize = hitSize;
            Variant = variant;
            Style = style;
            FocusNode = focusNode;
        }
        public IconData Icon { get; }
        public string? Tooltip { get; }
        public bool Enabled { get; }
        public float HitSize { get; }
        public ButtonVariant Variant { get; }
        public ButtonStyle? Style { get; }
        public FocusNode? FocusNode { get; }
        internal Action? OnPressed { get; }
        internal Action<VisualElement>? OnPressedWithAnchor { get; }
        internal override WidgetNode CreateNode() => new IconButtonNode(this);
    }
    internal sealed class IconButtonNode : WidgetNode {
        private UnityEngine.UIElements.Button? _button;
        private UnityEngine.UIElements.Image? _icon;
        private WidgetNode? _iconNode;
        private FocusNodeBinding? _focusBinding;
        private WidgetStates _appliedStates;
        private bool _hasStyleApplied;
        private bool _isHovered;
        private bool _isPressed;
        private bool _isFocused;
        public IconButtonNode(IconButton widget) : base(widget) { }
        protected override VisualElement CreateElement(BuildContext context) {
            var widget = (IconButton)Widget;
            _button = new UnityEngine.UIElements.Button { tooltip = widget.Tooltip ?? string.Empty };
            _button.style.backgroundImage = StyleKeyword.None;
            _button.style.borderTopWidth = 0f;
            _button.style.borderRightWidth = 0f;
            _button.style.borderBottomWidth = 0f;
            _button.style.borderLeftWidth = 0f;
            _button.style.marginTop = 0f;
            _button.style.marginRight = 0f;
            _button.style.marginBottom = 0f;
            _button.style.marginLeft = 0f;
            _button.style.width = widget.HitSize;
            _button.style.height = widget.HitSize;
            _button.style.minWidth = widget.HitSize;
            _button.style.minHeight = widget.HitSize;
            _button.style.justifyContent = Justify.Center;
            _button.style.alignItems = UnityEngine.UIElements.Align.Center;
            _button.SetEnabled(widget.Enabled);
            ApplyResolvedInteractionStyle();
            return _button;
        }
        protected override void OnMounted() {
            var foreground = EffectiveStyle?.ResolveForeground(ResolveStates());
            _iconNode = MountChild(new Icon(((IconButton)Widget).Icon, color: foreground), _button!);
            _icon = (UnityEngine.UIElements.Image)_button![0];
            ApplyStyle(ResolveStates(), force: true);
            _button!.clicked += HandleClicked;
            Bindings.Add(() => _button.clicked -= HandleClicked);
            _button.RegisterCallback<PointerEnterEvent>(HandlePointerEnter);
            _button.RegisterCallback<PointerLeaveEvent>(HandlePointerLeave);
            _button.RegisterCallback<PointerDownEvent>(HandlePointerDown);
            _button.RegisterCallback<PointerUpEvent>(HandlePointerUp);
            _button.RegisterCallback<FocusInEvent>(HandleFocusIn);
            _button.RegisterCallback<FocusOutEvent>(HandleFocusOut);
            Bindings.Add(UnregisterCallbacks);
            BindFocusNode((IconButton)Widget);
            Bindings.Add(ReleaseFocusBinding);
        }
        internal override bool TryUpdate(Widget nextWidget) {
            if (!CanUpdateWith(nextWidget) || nextWidget is not IconButton button) return false;
            var previous = (IconButton)Widget;
            UpdateWidget(button);
            _button!.tooltip = button.Tooltip ?? string.Empty;
            _button.SetEnabled(button.Enabled);
            _button.style.width = button.HitSize;
            _button.style.height = button.HitSize;
            _button.style.minWidth = button.HitSize;
            _button.style.minHeight = button.HitSize;
            if (!ReferenceEquals(previous.FocusNode, button.FocusNode)) {
                ReleaseFocusBinding();
                BindFocusNode(button);
            }

            _hasStyleApplied = false;
            ReevaluateInheritedDependencies(() =>
            {
                var foreground = EffectiveStyle?.ResolveForeground(ResolveStates());
                ReconcileSingleChild(ref _iconNode, new Icon(button.Icon, color: foreground), _button);
                _icon = (UnityEngine.UIElements.Image)_iconNode!.NativeElement;
                ApplyResolvedInteractionStyle();
                return true;
            });
            return true;
        }
        internal void HandleClicked() {
            if (!IsMounted || !((IconButton)Widget).Enabled) return;
            var widget = (IconButton)Widget;
            if (widget.OnPressedWithAnchor is { } anchored) anchored(_button!);
            else widget.OnPressed!.Invoke();
        }
        protected override SemanticsProperties DescribeSemantics() {
            var widget = (IconButton)Widget;
            return new SemanticsProperties(
                label: widget.Tooltip ?? widget.Icon.Name,
                role: SemanticsRole.Button,
                enabled: widget.Enabled,
                onTap: HandleClicked,
                onAccessibilityFocusChanged: focused => { if (focused) _button?.Focus(); });
        }
        private ButtonStyle? EffectiveStyle => ((IconButton)Widget).Style ?? Context.Theme?.ButtonTheme.Resolve(((IconButton)Widget).Variant);
        private void HandlePointerEnter(PointerEnterEvent _) => SetHovered(true);
        private void HandlePointerLeave(PointerLeaveEvent _) => SetHovered(false);
        private void HandlePointerDown(PointerDownEvent _) => SetPressed(true);
        private void HandlePointerUp(PointerUpEvent _) => SetPressed(false);
        private void HandleFocusIn(FocusInEvent _) => SetFocused(true);
        private void HandleFocusOut(FocusOutEvent _) => SetFocused(false);
        internal void SetHovered(bool value) { _isHovered = value; ApplyResolvedInteractionStyle(); }
        internal void SetPressed(bool value) { _isPressed = value; ApplyResolvedInteractionStyle(); }
        internal void SetFocused(bool value) { _isFocused = value; ApplyResolvedInteractionStyle(); }
        protected override void OnInheritedChanged(InheritedAspect aspect) {
            _hasStyleApplied = false;
            ApplyResolvedInteractionStyle();
        }
        private void ApplyResolvedInteractionStyle() {
            ApplyStyle(ResolveStates());
        }
        private WidgetStates ResolveStates() {
            var states = WidgetStates.None;
            if (!((IconButton)Widget).Enabled) states |= WidgetStates.Disabled;
            if (_isHovered) states |= WidgetStates.Hovered;
            if (_isFocused) states |= WidgetStates.Focused;
            if (_isPressed) states |= WidgetStates.Pressed;
            return states;
        }
        private void ApplyStyle(WidgetStates states, bool force = false) {
            var style = EffectiveStyle;
            if (!force && _hasStyleApplied && _appliedStates == states) return;
            _hasStyleApplied = true;
            _appliedStates = states;
            ClearAppliedStyle();
            if (style is null) return;
            if (style.ResolveBackground(states) is { } background) _button!.style.backgroundColor = background;
            var foreground = style.ResolveForeground(states);
            if (foreground is { } foregroundColor) {
                _button!.style.color = foregroundColor;
                if (_icon is not null) _icon.tintColor = foregroundColor;
            } else if (_icon is not null) {
                _icon.tintColor = Context.Theme?.IconTheme.Color ?? ThemeData.FallbackIconTheme.Color;
            }
            if (style.ResolveShape(states) is { } shape) {
                _button!.style.borderTopLeftRadius = shape.TopLeft;
                _button.style.borderTopRightRadius = shape.TopRight;
                _button.style.borderBottomRightRadius = shape.BottomRight;
                _button.style.borderBottomLeftRadius = shape.BottomLeft;
            }
            if (style.ResolveBorder(states) is { } border) BorderStyleMapper.Apply(_button!, border);
        }
        private void BindFocusNode(IconButton widget) {
            if (widget.FocusNode is { } focusNode) {
                _focusBinding = FocusNodeBinding.Attach(focusNode, _button!, Context.FocusTraversal);
            }
        }
        private void ReleaseFocusBinding() {
            _focusBinding?.Dispose();
            _focusBinding = null;
        }
        private void ClearAppliedStyle() {
            _button!.style.backgroundColor = StyleKeyword.Null;
            _button.style.color = StyleKeyword.Null;
            _button.style.borderTopLeftRadius = StyleKeyword.Null;
            _button.style.borderTopRightRadius = StyleKeyword.Null;
            _button.style.borderBottomRightRadius = StyleKeyword.Null;
            _button.style.borderBottomLeftRadius = StyleKeyword.Null;
            BorderStyleMapper.Apply(_button, Border.All(UnityEngine.Color.clear, 0f));
        }
        private void UnregisterCallbacks() {
            _button!.UnregisterCallback<PointerEnterEvent>(HandlePointerEnter);
            _button.UnregisterCallback<PointerLeaveEvent>(HandlePointerLeave);
            _button.UnregisterCallback<PointerDownEvent>(HandlePointerDown);
            _button.UnregisterCallback<PointerUpEvent>(HandlePointerUp);
            _button.UnregisterCallback<FocusInEvent>(HandleFocusIn);
            _button.UnregisterCallback<FocusOutEvent>(HandleFocusOut);
        }
    }

    /// <summary>
    /// Displays a native UI Toolkit button and invokes a callback when it is clicked.
    /// </summary>
    public sealed class Button : Widget {
        /// <summary>
        /// Creates a button.
        /// </summary>
        public Button(
            string text,
            Action onPressed,
            ButtonVariant variant = ButtonVariant.Primary,
            ButtonStyle? style = null,
            bool enabled = true,
            FocusNode? focusNode = null) {
            Text = text ?? throw new ArgumentNullException(nameof(text));
            Child = new Text(text);
            OnPressed = onPressed ?? throw new ArgumentNullException(nameof(onPressed));
            if (!Enum.IsDefined(typeof(ButtonVariant), variant)) {
                throw new ArgumentOutOfRangeException(nameof(variant));
            }

            Variant = variant;
            Style = style;
            Enabled = enabled;
            FocusNode = focusNode;
        }

        /// <summary>
        /// Creates a button whose content is an arbitrary widget tree.
        /// </summary>
        public Button(
            Widget child,
            Action onPressed,
            ButtonVariant variant = ButtonVariant.Primary,
            ButtonStyle? style = null,
            bool enabled = true,
            FocusNode? focusNode = null,
            string? semanticsLabel = null) {
            Child = child ?? throw new ArgumentNullException(nameof(child));
            OnPressed = onPressed ?? throw new ArgumentNullException(nameof(onPressed));
            if (!Enum.IsDefined(typeof(ButtonVariant), variant)) {
                throw new ArgumentOutOfRangeException(nameof(variant));
            }

            Text = string.Empty;
            Variant = variant;
            Style = style;
            Enabled = enabled;
            FocusNode = focusNode;
            SemanticsLabel = semanticsLabel;
            HasCustomChild = true;
        }

        /// <summary>Creates a child-based button with an explicit visual style.</summary>
        public Button(
            Widget child,
            Action onPressed,
            ButtonStyle buttonStyle,
            bool enabled = true,
            FocusNode? focusNode = null,
            string? semanticsLabel = null)
            : this(child, onPressed, ButtonVariant.Primary, buttonStyle, enabled, focusNode, semanticsLabel) {
        }

        /// <summary>
        /// Creates a button with an explicit visual style.
        /// </summary>
        public Button(
            string text,
            Action onPressed,
            ButtonStyle buttonStyle,
            bool enabled = true,
            FocusNode? focusNode = null)
            : this(text, onPressed, ButtonVariant.Primary, buttonStyle, enabled, focusNode) {
        }

        internal Button(
            string text,
            Action onPressed,
            ButtonVariant variant,
            ButtonStyle? style,
            bool enabled,
            FocusNode? focusNode,
            bool replaceFocusNodeAttachment)
            : this(text, onPressed, variant, style, enabled, focusNode) {
            ReplaceFocusNodeAttachment = replaceFocusNodeAttachment;
        }

        /// <summary>
        /// Gets the button label.
        /// </summary>
        public string Text { get; }

        /// <summary>Gets the declarative content hosted by this button.</summary>
        public Widget Child { get; }

        /// <summary>Gets the optional accessibility label for child-based buttons.</summary>
        public string? SemanticsLabel { get; }

        /// <summary>
        /// Gets the semantic button style.
        /// </summary>
        public ButtonStyle? Style { get; }

        /// <summary>
        /// Gets the semantic style selected when <see cref="Style"/> is not supplied.
        /// </summary>
        public ButtonVariant Variant { get; }

        /// <summary>
        /// Gets whether the button accepts input.
        /// </summary>
        public bool Enabled { get; }

        /// <summary>
        /// Optional externally owned controller for requesting and observing focus.
        /// </summary>
        public FocusNode? FocusNode { get; }

        // Reactive semantic controls may replace their native Button during a state
        // transition. This preserves one external controller across that handoff.
        internal bool ReplaceFocusNodeAttachment { get; }

        internal bool HasCustomChild { get; }

        internal Action OnPressed { get; }

        internal override WidgetNode CreateNode() {
            return new ButtonNode(this);
        }
    }

}
