#!/usr/bin/env python3
"""Generates the typed LumaFlow icon catalog from the checked-in manifest."""

import argparse
import json
import sys
from pathlib import Path


BEGIN = "        // <auto-generated: LumaIcons>"
END = "        // </auto-generated: LumaIcons>"
BRAND_ENTRIES = (
    {"name": "LumaFlow", "source": "lumaflow"},
)


def load_entries(manifest_path: Path):
    manifest = json.loads(manifest_path.read_text())
    return manifest["icons"]


def render_catalog(entries):
    catalog_entries = [*entries, *BRAND_ENTRIES]
    lines = [
        "    public static class LumaIcons {",
        BEGIN,
        "        // Generated by Tools/LumaFlow/Icons/generate_luma_icons.py. Do not edit by hand.",
    ]
    for entry in catalog_entries:
        lines.append(
            f'        public static IconData {entry["name"]} {{ get; }} = '
            f'new("{entry["name"]}", "LumaFlowIcons/{entry["source"]}");'
        )
    lines.extend([
        "",
        "        public static System.Collections.Generic.IReadOnlyList<IconData> All { get; } =",
        "            System.Array.AsReadOnly(new[]",
        "            {",
    ])
    for entry in catalog_entries:
        lines.append(f"            {entry['name']},")
    lines.extend(["            });"])
    lines.extend([END, "    }", ""])
    return "\n".join(lines)


def catalog_block(source: str):
    class_start = source.find("    public static class LumaIcons")
    marker_end = source.find(END, class_start)
    class_end = source.find("\n    }", marker_end)
    if class_start < 0 or marker_end < 0 or class_end < 0:
        raise ValueError("could not find the LumaIcons catalog block")
    return source[class_start:class_end + len("\n    }")]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--manifest",
        type=Path,
        default=Path(__file__).with_name("lucide-icons.json"),
    )
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check-catalog", type=Path)
    args = parser.parse_args()

    generated = render_catalog(load_entries(args.manifest))
    if args.output is not None:
        args.output.write_text("#nullable enable\n\nnamespace LumaFlow {\n" + generated + "}\n")

    if args.check_catalog is not None:
        actual = catalog_block(args.check_catalog.read_text())
        if actual != generated.rstrip("\n"):
            print("LumaIcons catalog is stale; run generate_luma_icons.py and update it.", file=sys.stderr)
            return 1

    if args.output is None and args.check_catalog is None:
        sys.stdout.write(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
