#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;

namespace LumaFlow.Editor {

    /// <summary>Creates the Runtime public API snapshot used by compatibility tests.</summary>
    internal static class PublicApiSnapshot {
        internal const string BaselineFileName = "PublicApiBaseline.txt";

        [MenuItem("Tools/LumaFlow/Validation/Write Public API Baseline")]
        private static void WriteBaselineFromMenu() {
            var path = WriteBaseline();
            AssetDatabase.Refresh();
            EditorUtility.DisplayDialog(
                "LumaFlow public API",
                $"Wrote the current Runtime API to:\n{path}\n\nReview this change before committing it.",
                "OK");
        }

        internal static string WriteBaseline() {
            var path = ResolveBaselinePath();
            File.WriteAllText(path, Capture(typeof(Widget).Assembly), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            return path;
        }

        internal static string ResolveBaselinePath() {
            var candidates = AssetDatabase.FindAssets("PublicApiBaseline")
                .Select(AssetDatabase.GUIDToAssetPath)
                .Where(path => path.EndsWith(BaselineFileName, StringComparison.Ordinal))
                .OrderBy(path => path, StringComparer.Ordinal)
                .ToArray();
            if (candidates.Length == 1) {
                return Path.GetFullPath(candidates[0]);
            }
            throw new InvalidOperationException(
                $"Could not resolve a unique {BaselineFileName}; found {candidates.Length} candidates.");
        }

        internal static string Capture(Assembly assembly) {
            if (assembly is null) throw new ArgumentNullException(nameof(assembly));
            var lines = new List<string> {
                "# LumaFlow.Runtime public API baseline",
                "# Generated by Tools > LumaFlow > Validation > Write Public API Baseline.",
                "# Review source and migration impact before updating this file.",
                string.Empty
            };

            var types = assembly.GetExportedTypes()
                .OrderBy(type => TypeName(type), StringComparer.Ordinal)
                .ToArray();
            for (var index = 0; index < types.Length; index++) {
                AppendType(lines, types[index]);
                lines.Add(string.Empty);
            }
            return string.Join("\n", lines).TrimEnd() + "\n";
        }

        private static void AppendType(ICollection<string> lines, Type type) {
            var obsolete = type.GetCustomAttribute<ObsoleteAttribute>();
            if (obsolete is not null) lines.Add(FormatObsolete(obsolete));
            lines.Add(FormatTypeDeclaration(type));

            var members = type.GetMembers(BindingFlags.Public | BindingFlags.NonPublic
                    | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)
                .Where(IsVisibleApi)
                .Select(FormatMember)
                .Where(signature => signature is not null)
                .Cast<string>()
                .Distinct(StringComparer.Ordinal)
                .OrderBy(signature => signature, StringComparer.Ordinal);
            foreach (var member in members) lines.Add("  " + member);
        }

        private static bool IsVisibleApi(MemberInfo member) => member switch {
            MethodBase method => IsVisible(method),
            FieldInfo field => field.IsPublic || field.IsFamily || field.IsFamilyOrAssembly,
            PropertyInfo property => IsVisible(property.GetMethod) || IsVisible(property.SetMethod),
            EventInfo eventInfo => IsVisible(eventInfo.AddMethod) || IsVisible(eventInfo.RemoveMethod),
            _ => false
        };

        private static bool IsVisible(MethodBase? method) => method is not null
            && (method.IsPublic || method.IsFamily || method.IsFamilyOrAssembly);

        private static string? FormatMember(MemberInfo member) {
            var obsolete = member.GetCustomAttribute<ObsoleteAttribute>();
            var prefix = obsolete is null ? string.Empty : FormatObsolete(obsolete) + " ";
            return member switch {
                ConstructorInfo constructor => prefix + FormatConstructor(constructor),
                MethodInfo method when !method.IsSpecialName => prefix + FormatMethod(method),
                FieldInfo field => prefix + FormatField(field),
                PropertyInfo property => prefix + FormatProperty(property),
                EventInfo eventInfo => prefix + FormatEvent(eventInfo),
                _ => null
            };
        }

        private static string FormatTypeDeclaration(Type type) {
            var accessibility = type.IsNested
                ? type.IsNestedPublic ? "public" : "protected"
                : "public";
            var modifiers = type.IsAbstract && type.IsSealed
                ? " static"
                : type.IsAbstract && !type.IsInterface
                    ? " abstract"
                    : type.IsSealed && !type.IsValueType && !typeof(Delegate).IsAssignableFrom(type)
                        ? " sealed"
                        : string.Empty;
            var kind = type.IsInterface ? "interface"
                : type.IsEnum ? "enum"
                : typeof(MulticastDelegate).IsAssignableFrom(type.BaseType) ? "delegate"
                : type.IsValueType ? "struct"
                : "class";
            var inheritance = new List<string>();
            if (type.BaseType is not null
                && type.BaseType != typeof(object)
                && type.BaseType != typeof(ValueType)
                && type.BaseType != typeof(Enum)
                && type.BaseType != typeof(MulticastDelegate)) {
                inheritance.Add(TypeName(type.BaseType));
            }
            inheritance.AddRange(type.GetInterfaces()
                .Select(TypeName)
                .OrderBy(name => name, StringComparer.Ordinal));
            var suffix = inheritance.Count == 0 ? string.Empty : " : " + string.Join(", ", inheritance);
            return $"{accessibility}{modifiers} {kind} {TypeName(type)}{suffix}";
        }

        private static string FormatConstructor(ConstructorInfo constructor) =>
            $"{Visibility(constructor)}{Static(constructor)} {SimpleTypeName(constructor.DeclaringType!)}({Parameters(constructor.GetParameters())})";

        private static string FormatMethod(MethodInfo method) {
            var generic = method.IsGenericMethodDefinition
                ? "<" + string.Join(", ", method.GetGenericArguments().Select(argument => argument.Name)) + ">"
                : string.Empty;
            var constraints = method.IsGenericMethodDefinition ? GenericConstraints(method.GetGenericArguments()) : string.Empty;
            return $"{Visibility(method)}{MethodModifiers(method)} {TypeName(method.ReturnType)} {method.Name}{generic}({Parameters(method.GetParameters())}){constraints}";
        }

        private static string FormatField(FieldInfo field) {
            var modifier = field.IsLiteral ? " const"
                : field.IsStatic && field.IsInitOnly ? " static readonly"
                : field.IsStatic ? " static"
                : field.IsInitOnly ? " readonly"
                : string.Empty;
            var value = field.IsLiteral ? " = " + Constant(field.GetRawConstantValue()) : string.Empty;
            return $"{Visibility(field)}{modifier} {TypeName(field.FieldType)} {field.Name}{value}";
        }

        private static string FormatProperty(PropertyInfo property) {
            var accessor = property.GetMethod ?? property.SetMethod!;
            var index = property.GetIndexParameters();
            var name = index.Length == 0 ? property.Name : $"this[{Parameters(index)}]";
            var get = IsVisible(property.GetMethod) ? AccessorVisibility(property.GetMethod!, accessor) + "get; " : string.Empty;
            var set = IsVisible(property.SetMethod) ? AccessorVisibility(property.SetMethod!, accessor) + "set; " : string.Empty;
            return $"{Visibility(accessor)}{Static(accessor)} {TypeName(property.PropertyType)} {name} {{ {get}{set}}}";
        }

        private static string FormatEvent(EventInfo eventInfo) {
            var accessor = eventInfo.AddMethod ?? eventInfo.RemoveMethod!;
            return $"{Visibility(accessor)}{Static(accessor)} event {TypeName(eventInfo.EventHandlerType!)} {eventInfo.Name}";
        }

        private static string Parameters(IEnumerable<ParameterInfo> parameters) => string.Join(", ", parameters.Select(parameter => {
            var modifier = parameter.IsOut ? "out "
                : parameter.ParameterType.IsByRef ? (parameter.IsIn ? "in " : "ref ")
                : parameter.GetCustomAttribute<ParamArrayAttribute>() is not null ? "params "
                : string.Empty;
            var type = parameter.ParameterType.IsByRef
                ? parameter.ParameterType.GetElementType()!
                : parameter.ParameterType;
            var optional = parameter.HasDefaultValue ? " = " + Constant(parameter.DefaultValue) : string.Empty;
            return $"{modifier}{TypeName(type)} {parameter.Name}{optional}";
        }));

        private static string MethodModifiers(MethodInfo method) {
            if (method.IsStatic) return " static";
            if (method.IsAbstract) return " abstract";
            if (!method.IsVirtual) return string.Empty;
            return method.GetBaseDefinition() != method ? " override" : " virtual";
        }

        private static string Static(MethodBase method) => method.IsStatic ? " static" : string.Empty;

        private static string Visibility(MethodBase method) => method.IsPublic ? "public"
            : method.IsFamilyOrAssembly ? "protected internal"
            : "protected";

        private static string Visibility(FieldInfo field) => field.IsPublic ? "public"
            : field.IsFamilyOrAssembly ? "protected internal"
            : "protected";

        private static string AccessorVisibility(MethodInfo accessor, MethodInfo primary) =>
            Visibility(accessor) == Visibility(primary) ? string.Empty : Visibility(accessor) + " ";

        private static string TypeName(Type type) {
            if (type.IsGenericParameter) return type.Name;
            if (type.IsArray) return TypeName(type.GetElementType()!) + "[" + new string(',', type.GetArrayRank() - 1) + "]";
            if (type.IsPointer) return TypeName(type.GetElementType()!) + "*";
            if (type.IsByRef) return TypeName(type.GetElementType()!);
            if (Nullable.GetUnderlyingType(type) is { } nullable) return TypeName(nullable) + "?";
            if (!type.IsGenericType) return PrimitiveAlias(type) ?? (type.FullName ?? type.Name).Replace('+', '.');
            var definition = type.GetGenericTypeDefinition();
            var name = (definition.FullName ?? definition.Name).Replace('+', '.');
            var tick = name.IndexOf('`');
            if (tick >= 0) name = name.Substring(0, tick);
            return name + "<" + string.Join(", ", type.GetGenericArguments().Select(TypeName)) + ">";
        }

        private static string SimpleTypeName(Type type) {
            var name = type.Name;
            var tick = name.IndexOf('`');
            return tick < 0 ? name : name.Substring(0, tick);
        }

        private static string? PrimitiveAlias(Type type) {
            if (type == typeof(void)) return "void";
            if (type == typeof(bool)) return "bool";
            if (type == typeof(byte)) return "byte";
            if (type == typeof(sbyte)) return "sbyte";
            if (type == typeof(short)) return "short";
            if (type == typeof(ushort)) return "ushort";
            if (type == typeof(int)) return "int";
            if (type == typeof(uint)) return "uint";
            if (type == typeof(long)) return "long";
            if (type == typeof(ulong)) return "ulong";
            if (type == typeof(float)) return "float";
            if (type == typeof(double)) return "double";
            if (type == typeof(decimal)) return "decimal";
            if (type == typeof(char)) return "char";
            if (type == typeof(string)) return "string";
            if (type == typeof(object)) return "object";
            return null;
        }

        private static string GenericConstraints(IEnumerable<Type> arguments) {
            var clauses = new List<string>();
            foreach (var argument in arguments) {
                var constraints = new List<string>();
                var attributes = argument.GenericParameterAttributes;
                if ((attributes & GenericParameterAttributes.ReferenceTypeConstraint) != 0) constraints.Add("class");
                if ((attributes & GenericParameterAttributes.NotNullableValueTypeConstraint) != 0) constraints.Add("struct");
                constraints.AddRange(argument.GetGenericParameterConstraints().Select(TypeName));
                if ((attributes & GenericParameterAttributes.DefaultConstructorConstraint) != 0
                    && (attributes & GenericParameterAttributes.NotNullableValueTypeConstraint) == 0) constraints.Add("new()");
                if (constraints.Count > 0) clauses.Add($" where {argument.Name} : {string.Join(", ", constraints)}");
            }
            return string.Concat(clauses);
        }

        private static string Constant(object? value) {
            if (value is null || value == DBNull.Value || value == Missing.Value) return "null";
            if (value is string text) return "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
            if (value is char character) return "'" + character + "'";
            if (value is bool boolean) return boolean ? "true" : "false";
            if (value is float single) return single.ToString("R", CultureInfo.InvariantCulture) + "f";
            if (value is double number) return number.ToString("R", CultureInfo.InvariantCulture);
            if (value.GetType().IsEnum) return TypeName(value.GetType()) + "." + value;
            return Convert.ToString(value, CultureInfo.InvariantCulture) ?? "null";
        }

        private static string FormatObsolete(ObsoleteAttribute obsolete) =>
            $"[Obsolete({Constant(obsolete.Message)}, error: {(obsolete.IsError ? "true" : "false")})]";
    }
}
