#nullable enable

using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;
using NativeButton = UnityEngine.UIElements.Button;
using NativeImage = UnityEngine.UIElements.Image;

namespace LumaFlow.Editor {
    /// <summary>Exports an initial visual snapshot using the existing runtime style mappers.</summary>
    public static class UxmlPreviewExporter {
        private static readonly XNamespace Ui = "UnityEngine.UIElements";
        private static readonly PropertyInfo[] Styles = typeof(IStyle).GetProperties()
            .OrderBy(property => property.Name, StringComparer.Ordinal).ToArray();

        public static (string Uxml, string Uss) Export(Widget widget, string styleFileName) {
            return Export(widget, styleFileName, Vector2.zero);
        }

        internal static (string Uxml, string Uss) Export(Widget widget, string styleFileName, Vector2 viewportSize) {
            if (Path.GetFileName(styleFileName) != styleFileName || !styleFileName.EndsWith(".uss", StringComparison.Ordinal))
                throw new ArgumentException("Provide a sibling .uss filename.", nameof(styleFileName));
            var root = new VisualElement();
            var previewWidget = viewportSize.x > 0f && viewportSize.y > 0f
                ? new MediaQuery(new MediaQueryData(viewportSize.x, viewportSize.y, disableAnimations: true), widget)
                : widget;
            using var mount = global::LumaFlow.LumaFlow.Mount(previewWidget, root);
            ValidateNodes(mount.CaptureDiagnostics().Root);
            var styles = new StringBuilder("/* Generated by LumaFlow preview. Edit the C# factory. */\n");
            var index = 0;
            var document = new XElement(Ui + "UXML", new XAttribute(XNamespace.Xmlns + "ui", Ui),
                new XElement("Style", new XAttribute("src", styleFileName)),
                Serialize(root[0], styles, ref index));
            return (document.ToString() + "\n", styles.ToString());
        }

        private static void ValidateNodes(WidgetDiagnosticsNode node) {
            if (node.WidgetType == typeof(Native).FullName
                || node.WidgetType.Contains("Animation") || node.WidgetType.Contains("Animated"))
                throw new NotSupportedException($"Preview export does not yet support {node.WidgetType}.");
            foreach (var child in node.Children) ValidateNodes(child);
        }

        private static XElement Serialize(VisualElement element, StringBuilder styles, ref int index) {
            var type = element.GetType();
            if (type != typeof(VisualElement) && type != typeof(Label)
                && type != typeof(NativeButton) && type != typeof(NativeImage))
                throw new NotSupportedException($"Preview export does not yet support native element {type.FullName}.");
            if (element.styleSheets.count != 0)
                throw new NotSupportedException("External stylesheets require an explicit preview adapter.");
            var className = "lf-preview-" + index++;
            var xml = new XElement(Ui + type.Name,
                new XAttribute("class", string.Join(" ", element.GetClasses().Append(className))),
                new XAttribute("name", element.name ?? ""),
                new XAttribute("picking-mode", element.pickingMode.ToString()),
                new XAttribute("focusable", element.focusable ? "true" : "false"),
                new XAttribute("tabindex", element.tabIndex),
                new XAttribute("enabled", element.enabledSelf ? "true" : "false"));
            if (element is TextElement text) {
                xml.Add(new XAttribute("text", text.text ?? ""));
                xml.Add(new XAttribute("enable-rich-text", text.enableRichText ? "true" : "false"));
            }
            if (element is NativeImage image) {
                if (image.vectorImage != null) xml.Add(new XAttribute("vector-image", AssetUri(image.vectorImage)));
                else if (image.sprite != null) xml.Add(new XAttribute("sprite", AssetUri(image.sprite)));
                else if (image.image != null) xml.Add(new XAttribute("image", AssetUri(image.image)));
                xml.Add(new XAttribute("scale-mode", image.scaleMode.ToString()));
                xml.Add(new XAttribute("tint-color", "#" + ColorUtility.ToHtmlStringRGBA(image.tintColor)));
            }
            styles.Append('.').Append(className).Append(" {\n");
            foreach (var property in Styles) {
                var wrapper = property.GetValue(element.style);
                if (wrapper == null) continue;
                var keywordProperty = wrapper.GetType().GetProperty("keyword");
                if (keywordProperty == null) continue;
                var keyword = (StyleKeyword)keywordProperty.GetValue(wrapper);
                if (keyword == StyleKeyword.Null) continue;
                var value = keyword == StyleKeyword.Undefined
                    ? FormatValue(wrapper.GetType().GetProperty("value")!.GetValue(wrapper), property.Name)
                    : CssName(keyword.ToString());
                styles.Append("  ").Append(CssName(property.Name)).Append(": ").Append(value).Append(";\n");
            }
            styles.Append("}\n");
            // These supported elements own ordinary children, not template-generated control parts.
            foreach (var child in element.Children()) xml.Add(Serialize(child, styles, ref index));
            return xml;
        }

        private static string FormatValue(object? value, string property) {
            switch (value) {
                case float number when !float.IsNaN(number) && !float.IsInfinity(number): return number.ToString("R", CultureInfo.InvariantCulture);
                case int integer: return integer.ToString(CultureInfo.InvariantCulture);
                case Length length: return length.value.ToString("R", CultureInfo.InvariantCulture) + (length.unit == LengthUnit.Percent ? "%" : "px");
                case Color color: return $"rgba({Mathf.RoundToInt(color.r * 255)}, {Mathf.RoundToInt(color.g * 255)}, {Mathf.RoundToInt(color.b * 255)}, {color.a.ToString("R", CultureInfo.InvariantCulture)})";
                case Enum enumeration: return CssName(enumeration.ToString());
                case Font font: return "url(\"" + AssetUri(font) + "\")";
                default: throw new NotSupportedException($"Preview export cannot serialize style '{property}' ({value?.GetType().Name}).");
            }
        }

        private static string CssName(string value) {
            var name = Regex.Replace(value, "([a-z0-9])([A-Z])", "$1-$2").ToLowerInvariant();
            return name.StartsWith("unity-", StringComparison.Ordinal) ? "-" + name : name;
        }

        private static string AssetUri(UnityEngine.Object asset) {
            if (!AssetDatabase.TryGetGUIDAndLocalFileIdentifier(asset, out string guid, out long fileId))
                throw new NotSupportedException($"Preview requires a saved asset: {asset.name}.");
            return $"project://database/{AssetDatabase.GetAssetPath(asset)}?fileID={fileId}&guid={guid}&type=3";
        }
    }
}
